// Code generated by ent, DO NOT EDIT.

package userteam

import (
	"time"
	"yupao-go/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldUserID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldTeamID, v))
}

// JoinTime applies equality check predicate on the "join_time" field. It's identical to JoinTimeEQ.
func JoinTime(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldJoinTime, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldUpdateTime, v))
}

// IsDelete applies equality check predicate on the "is_delete" field. It's identical to IsDeleteEQ.
func IsDelete(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldIsDelete, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldUserID, vs...))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldTeamID, vs...))
}

// JoinTimeEQ applies the EQ predicate on the "join_time" field.
func JoinTimeEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldJoinTime, v))
}

// JoinTimeNEQ applies the NEQ predicate on the "join_time" field.
func JoinTimeNEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldJoinTime, v))
}

// JoinTimeIn applies the In predicate on the "join_time" field.
func JoinTimeIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldJoinTime, vs...))
}

// JoinTimeNotIn applies the NotIn predicate on the "join_time" field.
func JoinTimeNotIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldJoinTime, vs...))
}

// JoinTimeGT applies the GT predicate on the "join_time" field.
func JoinTimeGT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGT(FieldJoinTime, v))
}

// JoinTimeGTE applies the GTE predicate on the "join_time" field.
func JoinTimeGTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGTE(FieldJoinTime, v))
}

// JoinTimeLT applies the LT predicate on the "join_time" field.
func JoinTimeLT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLT(FieldJoinTime, v))
}

// JoinTimeLTE applies the LTE predicate on the "join_time" field.
func JoinTimeLTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLTE(FieldJoinTime, v))
}

// JoinTimeIsNil applies the IsNil predicate on the "join_time" field.
func JoinTimeIsNil() predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIsNull(FieldJoinTime))
}

// JoinTimeNotNil applies the NotNil predicate on the "join_time" field.
func JoinTimeNotNil() predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotNull(FieldJoinTime))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLTE(FieldUpdateTime, v))
}

// IsDeleteEQ applies the EQ predicate on the "is_delete" field.
func IsDeleteEQ(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldEQ(FieldIsDelete, v))
}

// IsDeleteNEQ applies the NEQ predicate on the "is_delete" field.
func IsDeleteNEQ(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNEQ(FieldIsDelete, v))
}

// IsDeleteIn applies the In predicate on the "is_delete" field.
func IsDeleteIn(vs ...int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldIn(FieldIsDelete, vs...))
}

// IsDeleteNotIn applies the NotIn predicate on the "is_delete" field.
func IsDeleteNotIn(vs ...int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldNotIn(FieldIsDelete, vs...))
}

// IsDeleteGT applies the GT predicate on the "is_delete" field.
func IsDeleteGT(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGT(FieldIsDelete, v))
}

// IsDeleteGTE applies the GTE predicate on the "is_delete" field.
func IsDeleteGTE(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldGTE(FieldIsDelete, v))
}

// IsDeleteLT applies the LT predicate on the "is_delete" field.
func IsDeleteLT(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLT(FieldIsDelete, v))
}

// IsDeleteLTE applies the LTE predicate on the "is_delete" field.
func IsDeleteLTE(v int8) predicate.UserTeam {
	return predicate.UserTeam(sql.FieldLTE(FieldIsDelete, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserTeam {
	return predicate.UserTeam(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserTeam {
	return predicate.UserTeam(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.UserTeam {
	return predicate.UserTeam(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.UserTeam {
	return predicate.UserTeam(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserTeam) predicate.UserTeam {
	return predicate.UserTeam(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserTeam) predicate.UserTeam {
	return predicate.UserTeam(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserTeam) predicate.UserTeam {
	return predicate.UserTeam(sql.NotPredicates(p))
}
