// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UserColumns holds the columns for the "user" table.
	UserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Nullable: true, Size: 256},
		{Name: "user_account", Type: field.TypeString, Unique: true, Nullable: true, Size: 256},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "gender", Type: field.TypeInt8, Nullable: true},
		{Name: "user_password", Type: field.TypeString, Size: 512},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 128},
		{Name: "email", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "user_status", Type: field.TypeInt, Default: 0},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "is_delete", Type: field.TypeInt8, Default: 0},
		{Name: "user_role", Type: field.TypeInt, Default: 0},
		{Name: "planet_code", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "tags", Type: field.TypeString, Nullable: true, Size: 1024},
	}
	// UserTable holds the schema information for the "user" table.
	UserTable = &schema.Table{
		Name:       "user",
		Columns:    UserColumns,
		PrimaryKey: []*schema.Column{UserColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UserTable,
	}
)

func init() {
	UserTable.Annotation = &entsql.Annotation{
		Table: "user",
	}
}
