// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"yupao-go/ent/schema"
	"yupao-go/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescUserAccount is the schema descriptor for user_account field.
	userDescUserAccount := userFields[2].Descriptor()
	// user.UserAccountValidator is a validator for the "user_account" field. It is called by the builders before save.
	user.UserAccountValidator = userDescUserAccount.Validators[0].(func(string) error)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[3].Descriptor()
	// user.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	user.AvatarURLValidator = userDescAvatarURL.Validators[0].(func(string) error)
	// userDescUserPassword is the schema descriptor for user_password field.
	userDescUserPassword := userFields[5].Descriptor()
	// user.UserPasswordValidator is a validator for the "user_password" field. It is called by the builders before save.
	user.UserPasswordValidator = userDescUserPassword.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[6].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[7].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUserStatus is the schema descriptor for user_status field.
	userDescUserStatus := userFields[8].Descriptor()
	// user.DefaultUserStatus holds the default value on creation for the user_status field.
	user.DefaultUserStatus = userDescUserStatus.Default.(int)
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userFields[9].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userFields[10].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescIsDelete is the schema descriptor for is_delete field.
	userDescIsDelete := userFields[11].Descriptor()
	// user.DefaultIsDelete holds the default value on creation for the is_delete field.
	user.DefaultIsDelete = userDescIsDelete.Default.(int8)
	// userDescUserRole is the schema descriptor for user_role field.
	userDescUserRole := userFields[12].Descriptor()
	// user.DefaultUserRole holds the default value on creation for the user_role field.
	user.DefaultUserRole = userDescUserRole.Default.(int)
	// userDescPlanetCode is the schema descriptor for planet_code field.
	userDescPlanetCode := userFields[13].Descriptor()
	// user.PlanetCodeValidator is a validator for the "planet_code" field. It is called by the builders before save.
	user.PlanetCodeValidator = userDescPlanetCode.Validators[0].(func(string) error)
	// userDescTags is the schema descriptor for tags field.
	userDescTags := userFields[14].Descriptor()
	// user.TagsValidator is a validator for the "tags" field. It is called by the builders before save.
	user.TagsValidator = userDescTags.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(int64) error)
}
