// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/team"
	"yupao-go/ent/user"
	"yupao-go/ent/userteam"
	"yupao-go/internal/pkg/types"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamCreate is the builder for creating a Team entity.
type TeamCreate struct {
	config
	mutation *TeamMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TeamCreate) SetName(v string) *TeamCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *TeamCreate) SetDescription(v string) *TeamCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TeamCreate) SetNillableDescription(v *string) *TeamCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetMaxNum sets the "max_num" field.
func (_c *TeamCreate) SetMaxNum(v int) *TeamCreate {
	_c.mutation.SetMaxNum(v)
	return _c
}

// SetNillableMaxNum sets the "max_num" field if the given value is not nil.
func (_c *TeamCreate) SetNillableMaxNum(v *int) *TeamCreate {
	if v != nil {
		_c.SetMaxNum(*v)
	}
	return _c
}

// SetExpireTime sets the "expire_time" field.
func (_c *TeamCreate) SetExpireTime(v time.Time) *TeamCreate {
	_c.mutation.SetExpireTime(v)
	return _c
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_c *TeamCreate) SetNillableExpireTime(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetExpireTime(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TeamCreate) SetUserID(v int64) *TeamCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TeamCreate) SetStatus(v types.TeamStatus) *TeamCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TeamCreate) SetNillableStatus(v *types.TeamStatus) *TeamCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *TeamCreate) SetPassword(v string) *TeamCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *TeamCreate) SetNillablePassword(v *string) *TeamCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *TeamCreate) SetCreateTime(v time.Time) *TeamCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *TeamCreate) SetNillableCreateTime(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *TeamCreate) SetUpdateTime(v time.Time) *TeamCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *TeamCreate) SetNillableUpdateTime(v *time.Time) *TeamCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *TeamCreate) SetIsDelete(v int8) *TeamCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *TeamCreate) SetNillableIsDelete(v *int8) *TeamCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TeamCreate) SetID(v int64) *TeamCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetLeaderID sets the "leader" edge to the User entity by ID.
func (_c *TeamCreate) SetLeaderID(id int64) *TeamCreate {
	_c.mutation.SetLeaderID(id)
	return _c
}

// SetLeader sets the "leader" edge to the User entity.
func (_c *TeamCreate) SetLeader(v *User) *TeamCreate {
	return _c.SetLeaderID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the UserTeam entity by IDs.
func (_c *TeamCreate) AddMembershipIDs(ids ...int64) *TeamCreate {
	_c.mutation.AddMembershipIDs(ids...)
	return _c
}

// AddMemberships adds the "memberships" edges to the UserTeam entity.
func (_c *TeamCreate) AddMemberships(v ...*UserTeam) *TeamCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMembershipIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_c *TeamCreate) Mutation() *TeamMutation {
	return _c.mutation
}

// Save creates the Team in the database.
func (_c *TeamCreate) Save(ctx context.Context) (*Team, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TeamCreate) SaveX(ctx context.Context) *Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TeamCreate) defaults() {
	if _, ok := _c.mutation.MaxNum(); !ok {
		v := team.DefaultMaxNum
		_c.mutation.SetMaxNum(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := team.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := team.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := team.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := team.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TeamCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Team.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := team.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Team.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxNum(); !ok {
		return &ValidationError{Name: "max_num", err: errors.New(`ent: missing required field "Team.max_num"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Team.user_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Team.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := team.StatusValidator(int(v)); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := team.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Team.password": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Team.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Team.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "Team.is_delete"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := team.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Team.id": %w`, err)}
		}
	}
	if len(_c.mutation.LeaderIDs()) == 0 {
		return &ValidationError{Name: "leader", err: errors.New(`ent: missing required edge "Team.leader"`)}
	}
	return nil
}

func (_c *TeamCreate) sqlSave(ctx context.Context) (*Team, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TeamCreate) createSpec() (*Team, *sqlgraph.CreateSpec) {
	var (
		_node = &Team{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(team.Table, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(team.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.MaxNum(); ok {
		_spec.SetField(team.FieldMaxNum, field.TypeInt, value)
		_node.MaxNum = value
	}
	if value, ok := _c.mutation.ExpireTime(); ok {
		_spec.SetField(team.FieldExpireTime, field.TypeTime, value)
		_node.ExpireTime = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeInt, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(team.FieldPassword, field.TypeString, value)
		_node.Password = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(team.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(team.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(team.FieldIsDelete, field.TypeInt8, value)
		_node.IsDelete = value
	}
	if nodes := _c.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.LeaderTable,
			Columns: []string{team.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TeamCreateBulk is the builder for creating many Team entities in bulk.
type TeamCreateBulk struct {
	config
	err      error
	builders []*TeamCreate
}

// Save creates the Team entities in the database.
func (_c *TeamCreateBulk) Save(ctx context.Context) ([]*Team, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Team, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TeamCreateBulk) SaveX(ctx context.Context) []*Team {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TeamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TeamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
