// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/predicate"
	"yupao-go/ent/team"
	"yupao-go/ent/user"
	"yupao-go/ent/userteam"
	"yupao-go/internal/pkg/types"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamUpdate is the builder for updating Team entities.
type TeamUpdate struct {
	config
	hooks    []Hook
	mutation *TeamMutation
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdate) Where(ps ...predicate.Team) *TeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TeamUpdate) SetName(v string) *TeamUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableName(v *string) *TeamUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamUpdate) SetDescription(v string) *TeamUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableDescription(v *string) *TeamUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamUpdate) ClearDescription() *TeamUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetMaxNum sets the "max_num" field.
func (_u *TeamUpdate) SetMaxNum(v int) *TeamUpdate {
	_u.mutation.ResetMaxNum()
	_u.mutation.SetMaxNum(v)
	return _u
}

// SetNillableMaxNum sets the "max_num" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableMaxNum(v *int) *TeamUpdate {
	if v != nil {
		_u.SetMaxNum(*v)
	}
	return _u
}

// AddMaxNum adds value to the "max_num" field.
func (_u *TeamUpdate) AddMaxNum(v int) *TeamUpdate {
	_u.mutation.AddMaxNum(v)
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TeamUpdate) SetExpireTime(v time.Time) *TeamUpdate {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableExpireTime(v *time.Time) *TeamUpdate {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TeamUpdate) ClearExpireTime() *TeamUpdate {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamUpdate) SetUserID(v int64) *TeamUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableUserID(v *int64) *TeamUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamUpdate) SetStatus(v types.TeamStatus) *TeamUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableStatus(v *types.TeamStatus) *TeamUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TeamUpdate) AddStatus(v types.TeamStatus) *TeamUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPassword sets the "password" field.
func (_u *TeamUpdate) SetPassword(v string) *TeamUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *TeamUpdate) SetNillablePassword(v *string) *TeamUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *TeamUpdate) ClearPassword() *TeamUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TeamUpdate) SetUpdateTime(v time.Time) *TeamUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *TeamUpdate) SetIsDelete(v int8) *TeamUpdate {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *TeamUpdate) SetNillableIsDelete(v *int8) *TeamUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *TeamUpdate) AddIsDelete(v int8) *TeamUpdate {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetLeaderID sets the "leader" edge to the User entity by ID.
func (_u *TeamUpdate) SetLeaderID(id int64) *TeamUpdate {
	_u.mutation.SetLeaderID(id)
	return _u
}

// SetLeader sets the "leader" edge to the User entity.
func (_u *TeamUpdate) SetLeader(v *User) *TeamUpdate {
	return _u.SetLeaderID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the UserTeam entity by IDs.
func (_u *TeamUpdate) AddMembershipIDs(ids ...int64) *TeamUpdate {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserTeam entity.
func (_u *TeamUpdate) AddMemberships(v ...*UserTeam) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdate) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearLeader clears the "leader" edge to the User entity.
func (_u *TeamUpdate) ClearLeader() *TeamUpdate {
	_u.mutation.ClearLeader()
	return _u
}

// ClearMemberships clears all "memberships" edges to the UserTeam entity.
func (_u *TeamUpdate) ClearMemberships() *TeamUpdate {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserTeam entities by IDs.
func (_u *TeamUpdate) RemoveMembershipIDs(ids ...int64) *TeamUpdate {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserTeam entities.
func (_u *TeamUpdate) RemoveMemberships(v ...*UserTeam) *TeamUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TeamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := team.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := team.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Team.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := team.StatusValidator(int(v)); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := team.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Team.password": %w`, err)}
		}
	}
	if _u.mutation.LeaderCleared() && len(_u.mutation.LeaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.leader"`)
	}
	return nil
}

func (_u *TeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(team.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(team.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MaxNum(); ok {
		_spec.SetField(team.FieldMaxNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxNum(); ok {
		_spec.AddField(team.FieldMaxNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(team.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(team.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(team.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(team.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(team.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(team.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(team.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(team.FieldIsDelete, field.TypeInt8, value)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.LeaderTable,
			Columns: []string{team.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.LeaderTable,
			Columns: []string{team.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TeamUpdateOne is the builder for updating a single Team entity.
type TeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TeamMutation
}

// SetName sets the "name" field.
func (_u *TeamUpdateOne) SetName(v string) *TeamUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableName(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *TeamUpdateOne) SetDescription(v string) *TeamUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableDescription(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TeamUpdateOne) ClearDescription() *TeamUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetMaxNum sets the "max_num" field.
func (_u *TeamUpdateOne) SetMaxNum(v int) *TeamUpdateOne {
	_u.mutation.ResetMaxNum()
	_u.mutation.SetMaxNum(v)
	return _u
}

// SetNillableMaxNum sets the "max_num" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableMaxNum(v *int) *TeamUpdateOne {
	if v != nil {
		_u.SetMaxNum(*v)
	}
	return _u
}

// AddMaxNum adds value to the "max_num" field.
func (_u *TeamUpdateOne) AddMaxNum(v int) *TeamUpdateOne {
	_u.mutation.AddMaxNum(v)
	return _u
}

// SetExpireTime sets the "expire_time" field.
func (_u *TeamUpdateOne) SetExpireTime(v time.Time) *TeamUpdateOne {
	_u.mutation.SetExpireTime(v)
	return _u
}

// SetNillableExpireTime sets the "expire_time" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableExpireTime(v *time.Time) *TeamUpdateOne {
	if v != nil {
		_u.SetExpireTime(*v)
	}
	return _u
}

// ClearExpireTime clears the value of the "expire_time" field.
func (_u *TeamUpdateOne) ClearExpireTime() *TeamUpdateOne {
	_u.mutation.ClearExpireTime()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TeamUpdateOne) SetUserID(v int64) *TeamUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableUserID(v *int64) *TeamUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TeamUpdateOne) SetStatus(v types.TeamStatus) *TeamUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableStatus(v *types.TeamStatus) *TeamUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *TeamUpdateOne) AddStatus(v types.TeamStatus) *TeamUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetPassword sets the "password" field.
func (_u *TeamUpdateOne) SetPassword(v string) *TeamUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillablePassword(v *string) *TeamUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *TeamUpdateOne) ClearPassword() *TeamUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *TeamUpdateOne) SetUpdateTime(v time.Time) *TeamUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *TeamUpdateOne) SetIsDelete(v int8) *TeamUpdateOne {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *TeamUpdateOne) SetNillableIsDelete(v *int8) *TeamUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *TeamUpdateOne) AddIsDelete(v int8) *TeamUpdateOne {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetLeaderID sets the "leader" edge to the User entity by ID.
func (_u *TeamUpdateOne) SetLeaderID(id int64) *TeamUpdateOne {
	_u.mutation.SetLeaderID(id)
	return _u
}

// SetLeader sets the "leader" edge to the User entity.
func (_u *TeamUpdateOne) SetLeader(v *User) *TeamUpdateOne {
	return _u.SetLeaderID(v.ID)
}

// AddMembershipIDs adds the "memberships" edge to the UserTeam entity by IDs.
func (_u *TeamUpdateOne) AddMembershipIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.AddMembershipIDs(ids...)
	return _u
}

// AddMemberships adds the "memberships" edges to the UserTeam entity.
func (_u *TeamUpdateOne) AddMemberships(v ...*UserTeam) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMembershipIDs(ids...)
}

// Mutation returns the TeamMutation object of the builder.
func (_u *TeamUpdateOne) Mutation() *TeamMutation {
	return _u.mutation
}

// ClearLeader clears the "leader" edge to the User entity.
func (_u *TeamUpdateOne) ClearLeader() *TeamUpdateOne {
	_u.mutation.ClearLeader()
	return _u
}

// ClearMemberships clears all "memberships" edges to the UserTeam entity.
func (_u *TeamUpdateOne) ClearMemberships() *TeamUpdateOne {
	_u.mutation.ClearMemberships()
	return _u
}

// RemoveMembershipIDs removes the "memberships" edge to UserTeam entities by IDs.
func (_u *TeamUpdateOne) RemoveMembershipIDs(ids ...int64) *TeamUpdateOne {
	_u.mutation.RemoveMembershipIDs(ids...)
	return _u
}

// RemoveMemberships removes "memberships" edges to UserTeam entities.
func (_u *TeamUpdateOne) RemoveMemberships(v ...*UserTeam) *TeamUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMembershipIDs(ids...)
}

// Where appends a list predicates to the TeamUpdate builder.
func (_u *TeamUpdateOne) Where(ps ...predicate.Team) *TeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TeamUpdateOne) Select(field string, fields ...string) *TeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Team entity.
func (_u *TeamUpdateOne) Save(ctx context.Context) (*Team, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TeamUpdateOne) SaveX(ctx context.Context) *Team {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TeamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := team.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TeamUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := team.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Team.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := team.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Team.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := team.StatusValidator(int(v)); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Team.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := team.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Team.password": %w`, err)}
		}
	}
	if _u.mutation.LeaderCleared() && len(_u.mutation.LeaderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Team.leader"`)
	}
	return nil
}

func (_u *TeamUpdateOne) sqlSave(ctx context.Context) (_node *Team, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(team.Table, team.Columns, sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Team.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, team.FieldID)
		for _, f := range fields {
			if !team.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != team.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(team.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(team.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(team.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.MaxNum(); ok {
		_spec.SetField(team.FieldMaxNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxNum(); ok {
		_spec.AddField(team.FieldMaxNum, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpireTime(); ok {
		_spec.SetField(team.FieldExpireTime, field.TypeTime, value)
	}
	if _u.mutation.ExpireTimeCleared() {
		_spec.ClearField(team.FieldExpireTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(team.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(team.FieldStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(team.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(team.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(team.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(team.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(team.FieldIsDelete, field.TypeInt8, value)
	}
	if _u.mutation.LeaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.LeaderTable,
			Columns: []string{team.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LeaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   team.LeaderTable,
			Columns: []string{team.LeaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !_u.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   team.MembershipsTable,
			Columns: []string{team.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Team{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{team.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
