// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/team"
	"yupao-go/ent/user"
	"yupao-go/ent/userteam"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTeamCreate is the builder for creating a UserTeam entity.
type UserTeamCreate struct {
	config
	mutation *UserTeamMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserTeamCreate) SetUserID(v int64) *UserTeamCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTeamID sets the "team_id" field.
func (_c *UserTeamCreate) SetTeamID(v int64) *UserTeamCreate {
	_c.mutation.SetTeamID(v)
	return _c
}

// SetJoinTime sets the "join_time" field.
func (_c *UserTeamCreate) SetJoinTime(v time.Time) *UserTeamCreate {
	_c.mutation.SetJoinTime(v)
	return _c
}

// SetNillableJoinTime sets the "join_time" field if the given value is not nil.
func (_c *UserTeamCreate) SetNillableJoinTime(v *time.Time) *UserTeamCreate {
	if v != nil {
		_c.SetJoinTime(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *UserTeamCreate) SetCreateTime(v time.Time) *UserTeamCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *UserTeamCreate) SetNillableCreateTime(v *time.Time) *UserTeamCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *UserTeamCreate) SetUpdateTime(v time.Time) *UserTeamCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *UserTeamCreate) SetNillableUpdateTime(v *time.Time) *UserTeamCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *UserTeamCreate) SetIsDelete(v int8) *UserTeamCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *UserTeamCreate) SetNillableIsDelete(v *int8) *UserTeamCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserTeamCreate) SetID(v int64) *UserTeamCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserTeamCreate) SetUser(v *User) *UserTeamCreate {
	return _c.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_c *UserTeamCreate) SetTeam(v *Team) *UserTeamCreate {
	return _c.SetTeamID(v.ID)
}

// Mutation returns the UserTeamMutation object of the builder.
func (_c *UserTeamCreate) Mutation() *UserTeamMutation {
	return _c.mutation
}

// Save creates the UserTeam in the database.
func (_c *UserTeamCreate) Save(ctx context.Context) (*UserTeam, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserTeamCreate) SaveX(ctx context.Context) *UserTeam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTeamCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTeamCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserTeamCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := userteam.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := userteam.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := userteam.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserTeamCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserTeam.user_id"`)}
	}
	if _, ok := _c.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "UserTeam.team_id"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "UserTeam.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "UserTeam.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "UserTeam.is_delete"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := userteam.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "UserTeam.id": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserTeam.user"`)}
	}
	if len(_c.mutation.TeamIDs()) == 0 {
		return &ValidationError{Name: "team", err: errors.New(`ent: missing required edge "UserTeam.team"`)}
	}
	return nil
}

func (_c *UserTeamCreate) sqlSave(ctx context.Context) (*UserTeam, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserTeamCreate) createSpec() (*UserTeam, *sqlgraph.CreateSpec) {
	var (
		_node = &UserTeam{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userteam.Table, sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.JoinTime(); ok {
		_spec.SetField(userteam.FieldJoinTime, field.TypeTime, value)
		_node.JoinTime = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(userteam.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(userteam.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(userteam.FieldIsDelete, field.TypeInt8, value)
		_node.IsDelete = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.UserTable,
			Columns: []string{userteam.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.TeamTable,
			Columns: []string{userteam.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserTeamCreateBulk is the builder for creating many UserTeam entities in bulk.
type UserTeamCreateBulk struct {
	config
	err      error
	builders []*UserTeamCreate
}

// Save creates the UserTeam entities in the database.
func (_c *UserTeamCreateBulk) Save(ctx context.Context) ([]*UserTeam, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserTeam, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserTeamMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserTeamCreateBulk) SaveX(ctx context.Context) []*UserTeam {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserTeamCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserTeamCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
