// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/predicate"
	"yupao-go/ent/team"
	"yupao-go/ent/user"
	"yupao-go/ent/userteam"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserTeamUpdate is the builder for updating UserTeam entities.
type UserTeamUpdate struct {
	config
	hooks    []Hook
	mutation *UserTeamMutation
}

// Where appends a list predicates to the UserTeamUpdate builder.
func (_u *UserTeamUpdate) Where(ps ...predicate.UserTeam) *UserTeamUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserTeamUpdate) SetUserID(v int64) *UserTeamUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTeamUpdate) SetNillableUserID(v *int64) *UserTeamUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *UserTeamUpdate) SetTeamID(v int64) *UserTeamUpdate {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *UserTeamUpdate) SetNillableTeamID(v *int64) *UserTeamUpdate {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetJoinTime sets the "join_time" field.
func (_u *UserTeamUpdate) SetJoinTime(v time.Time) *UserTeamUpdate {
	_u.mutation.SetJoinTime(v)
	return _u
}

// SetNillableJoinTime sets the "join_time" field if the given value is not nil.
func (_u *UserTeamUpdate) SetNillableJoinTime(v *time.Time) *UserTeamUpdate {
	if v != nil {
		_u.SetJoinTime(*v)
	}
	return _u
}

// ClearJoinTime clears the value of the "join_time" field.
func (_u *UserTeamUpdate) ClearJoinTime() *UserTeamUpdate {
	_u.mutation.ClearJoinTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserTeamUpdate) SetUpdateTime(v time.Time) *UserTeamUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserTeamUpdate) SetIsDelete(v int8) *UserTeamUpdate {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserTeamUpdate) SetNillableIsDelete(v *int8) *UserTeamUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *UserTeamUpdate) AddIsDelete(v int8) *UserTeamUpdate {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTeamUpdate) SetUser(v *User) *UserTeamUpdate {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *UserTeamUpdate) SetTeam(v *Team) *UserTeamUpdate {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the UserTeamMutation object of the builder.
func (_u *UserTeamUpdate) Mutation() *UserTeamMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTeamUpdate) ClearUser() *UserTeamUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *UserTeamUpdate) ClearTeam() *UserTeamUpdate {
	_u.mutation.ClearTeam()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserTeamUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTeamUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserTeamUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTeamUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTeamUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userteam.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTeamUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTeam.user"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTeam.team"`)
	}
	return nil
}

func (_u *UserTeamUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userteam.Table, userteam.Columns, sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinTime(); ok {
		_spec.SetField(userteam.FieldJoinTime, field.TypeTime, value)
	}
	if _u.mutation.JoinTimeCleared() {
		_spec.ClearField(userteam.FieldJoinTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userteam.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(userteam.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(userteam.FieldIsDelete, field.TypeInt8, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.UserTable,
			Columns: []string{userteam.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.UserTable,
			Columns: []string{userteam.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.TeamTable,
			Columns: []string{userteam.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.TeamTable,
			Columns: []string{userteam.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userteam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserTeamUpdateOne is the builder for updating a single UserTeam entity.
type UserTeamUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserTeamMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserTeamUpdateOne) SetUserID(v int64) *UserTeamUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserTeamUpdateOne) SetNillableUserID(v *int64) *UserTeamUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTeamID sets the "team_id" field.
func (_u *UserTeamUpdateOne) SetTeamID(v int64) *UserTeamUpdateOne {
	_u.mutation.SetTeamID(v)
	return _u
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (_u *UserTeamUpdateOne) SetNillableTeamID(v *int64) *UserTeamUpdateOne {
	if v != nil {
		_u.SetTeamID(*v)
	}
	return _u
}

// SetJoinTime sets the "join_time" field.
func (_u *UserTeamUpdateOne) SetJoinTime(v time.Time) *UserTeamUpdateOne {
	_u.mutation.SetJoinTime(v)
	return _u
}

// SetNillableJoinTime sets the "join_time" field if the given value is not nil.
func (_u *UserTeamUpdateOne) SetNillableJoinTime(v *time.Time) *UserTeamUpdateOne {
	if v != nil {
		_u.SetJoinTime(*v)
	}
	return _u
}

// ClearJoinTime clears the value of the "join_time" field.
func (_u *UserTeamUpdateOne) ClearJoinTime() *UserTeamUpdateOne {
	_u.mutation.ClearJoinTime()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserTeamUpdateOne) SetUpdateTime(v time.Time) *UserTeamUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserTeamUpdateOne) SetIsDelete(v int8) *UserTeamUpdateOne {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserTeamUpdateOne) SetNillableIsDelete(v *int8) *UserTeamUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *UserTeamUpdateOne) AddIsDelete(v int8) *UserTeamUpdateOne {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserTeamUpdateOne) SetUser(v *User) *UserTeamUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (_u *UserTeamUpdateOne) SetTeam(v *Team) *UserTeamUpdateOne {
	return _u.SetTeamID(v.ID)
}

// Mutation returns the UserTeamMutation object of the builder.
func (_u *UserTeamUpdateOne) Mutation() *UserTeamMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserTeamUpdateOne) ClearUser() *UserTeamUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearTeam clears the "team" edge to the Team entity.
func (_u *UserTeamUpdateOne) ClearTeam() *UserTeamUpdateOne {
	_u.mutation.ClearTeam()
	return _u
}

// Where appends a list predicates to the UserTeamUpdate builder.
func (_u *UserTeamUpdateOne) Where(ps ...predicate.UserTeam) *UserTeamUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserTeamUpdateOne) Select(field string, fields ...string) *UserTeamUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserTeam entity.
func (_u *UserTeamUpdateOne) Save(ctx context.Context) (*UserTeam, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserTeamUpdateOne) SaveX(ctx context.Context) *UserTeam {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserTeamUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserTeamUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserTeamUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := userteam.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserTeamUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTeam.user"`)
	}
	if _u.mutation.TeamCleared() && len(_u.mutation.TeamIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserTeam.team"`)
	}
	return nil
}

func (_u *UserTeamUpdateOne) sqlSave(ctx context.Context) (_node *UserTeam, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userteam.Table, userteam.Columns, sqlgraph.NewFieldSpec(userteam.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserTeam.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userteam.FieldID)
		for _, f := range fields {
			if !userteam.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != userteam.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JoinTime(); ok {
		_spec.SetField(userteam.FieldJoinTime, field.TypeTime, value)
	}
	if _u.mutation.JoinTimeCleared() {
		_spec.ClearField(userteam.FieldJoinTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(userteam.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(userteam.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(userteam.FieldIsDelete, field.TypeInt8, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.UserTable,
			Columns: []string{userteam.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.UserTable,
			Columns: []string{userteam.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TeamCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.TeamTable,
			Columns: []string{userteam.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userteam.TeamTable,
			Columns: []string{userteam.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserTeam{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userteam.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
