// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/user"
	"yupao-go/internal/shared/usertype"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (_c *UserCreate) SetUsername(v string) *UserCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_c *UserCreate) SetNillableUsername(v *string) *UserCreate {
	if v != nil {
		_c.SetUsername(*v)
	}
	return _c
}

// SetUserAccount sets the "user_account" field.
func (_c *UserCreate) SetUserAccount(v string) *UserCreate {
	_c.mutation.SetUserAccount(v)
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *UserCreate) SetAvatarURL(v string) *UserCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *UserCreate) SetNillableAvatarURL(v *string) *UserCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetGender sets the "gender" field.
func (_c *UserCreate) SetGender(v usertype.Gender) *UserCreate {
	_c.mutation.SetGender(v)
	return _c
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_c *UserCreate) SetNillableGender(v *usertype.Gender) *UserCreate {
	if v != nil {
		_c.SetGender(*v)
	}
	return _c
}

// SetUserPassword sets the "user_password" field.
func (_c *UserCreate) SetUserPassword(v string) *UserCreate {
	_c.mutation.SetUserPassword(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *UserCreate) SetPhone(v string) *UserCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_c *UserCreate) SetNillablePhone(v *string) *UserCreate {
	if v != nil {
		_c.SetPhone(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserCreate) SetEmail(v string) *UserCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *UserCreate) SetNillableEmail(v *string) *UserCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetUserStatus sets the "user_status" field.
func (_c *UserCreate) SetUserStatus(v int) *UserCreate {
	_c.mutation.SetUserStatus(v)
	return _c
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserStatus(v *int) *UserCreate {
	if v != nil {
		_c.SetUserStatus(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *UserCreate) SetCreateTime(v time.Time) *UserCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableCreateTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *UserCreate) SetUpdateTime(v time.Time) *UserCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *UserCreate) SetNillableUpdateTime(v *time.Time) *UserCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetIsDelete sets the "is_delete" field.
func (_c *UserCreate) SetIsDelete(v int8) *UserCreate {
	_c.mutation.SetIsDelete(v)
	return _c
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_c *UserCreate) SetNillableIsDelete(v *int8) *UserCreate {
	if v != nil {
		_c.SetIsDelete(*v)
	}
	return _c
}

// SetUserRole sets the "user_role" field.
func (_c *UserCreate) SetUserRole(v int) *UserCreate {
	_c.mutation.SetUserRole(v)
	return _c
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_c *UserCreate) SetNillableUserRole(v *int) *UserCreate {
	if v != nil {
		_c.SetUserRole(*v)
	}
	return _c
}

// SetPlanetCode sets the "planet_code" field.
func (_c *UserCreate) SetPlanetCode(v string) *UserCreate {
	_c.mutation.SetPlanetCode(v)
	return _c
}

// SetTags sets the "tags" field.
func (_c *UserCreate) SetTags(v string) *UserCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_c *UserCreate) SetNillableTags(v *string) *UserCreate {
	if v != nil {
		_c.SetTags(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserCreate) SetID(v int64) *UserCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the UserMutation object of the builder.
func (_c *UserCreate) Mutation() *UserMutation {
	return _c.mutation
}

// Save creates the User in the database.
func (_c *UserCreate) Save(ctx context.Context) (*User, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserCreate) SaveX(ctx context.Context) *User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserCreate) defaults() {
	if _, ok := _c.mutation.UserStatus(); !ok {
		v := user.DefaultUserStatus
		_c.mutation.SetUserStatus(v)
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := user.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := user.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		v := user.DefaultIsDelete
		_c.mutation.SetIsDelete(v)
	}
	if _, ok := _c.mutation.UserRole(); !ok {
		v := user.DefaultUserRole
		_c.mutation.SetUserRole(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserCreate) check() error {
	if v, ok := _c.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserAccount(); !ok {
		return &ValidationError{Name: "user_account", err: errors.New(`ent: missing required field "User.user_account"`)}
	}
	if v, ok := _c.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if v, ok := _c.mutation.AvatarURL(); ok {
		if err := user.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "User.avatar_url": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Gender(); ok {
		if err := user.GenderValidator(int8(v)); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserPassword(); !ok {
		return &ValidationError{Name: "user_password", err: errors.New(`ent: missing required field "User.user_password"`)}
	}
	if v, ok := _c.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "User.phone": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserStatus(); !ok {
		return &ValidationError{Name: "user_status", err: errors.New(`ent: missing required field "User.user_status"`)}
	}
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "User.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "User.update_time"`)}
	}
	if _, ok := _c.mutation.IsDelete(); !ok {
		return &ValidationError{Name: "is_delete", err: errors.New(`ent: missing required field "User.is_delete"`)}
	}
	if _, ok := _c.mutation.UserRole(); !ok {
		return &ValidationError{Name: "user_role", err: errors.New(`ent: missing required field "User.user_role"`)}
	}
	if _, ok := _c.mutation.PlanetCode(); !ok {
		return &ValidationError{Name: "planet_code", err: errors.New(`ent: missing required field "User.planet_code"`)}
	}
	if v, ok := _c.mutation.PlanetCode(); ok {
		if err := user.PlanetCodeValidator(v); err != nil {
			return &ValidationError{Name: "planet_code", err: fmt.Errorf(`ent: validator failed for field "User.planet_code": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Tags(); ok {
		if err := user.TagsValidator(v); err != nil {
			return &ValidationError{Name: "tags", err: fmt.Errorf(`ent: validator failed for field "User.tags": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := user.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "User.id": %w`, err)}
		}
	}
	return nil
}

func (_c *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = &value
	}
	if value, ok := _c.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
		_node.UserAccount = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = &value
	}
	if value, ok := _c.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeInt8, value)
		_node.Gender = &value
	}
	if value, ok := _c.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
		_node.UserPassword = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
		_node.Phone = &value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := _c.mutation.UserStatus(); ok {
		_spec.SetField(user.FieldUserStatus, field.TypeInt, value)
		_node.UserStatus = value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(user.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeInt8, value)
		_node.IsDelete = value
	}
	if value, ok := _c.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeInt, value)
		_node.UserRole = value
	}
	if value, ok := _c.mutation.PlanetCode(); ok {
		_spec.SetField(user.FieldPlanetCode, field.TypeString, value)
		_node.PlanetCode = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeString, value)
		_node.Tags = value
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (_c *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*User, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
