// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"yupao-go/ent/predicate"
	"yupao-go/ent/user"
	"yupao-go/internal/shared/usertype"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdate) ClearUsername() *UserUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetUserAccount sets the "user_account" field.
func (_u *UserUpdate) SetUserAccount(v string) *UserUpdate {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserAccount(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdate) SetAvatarURL(v string) *UserUpdate {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatarURL(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdate) ClearAvatarURL() *UserUpdate {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdate) SetGender(v usertype.Gender) *UserUpdate {
	_u.mutation.ResetGender()
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGender(v *usertype.Gender) *UserUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// AddGender adds value to the "gender" field.
func (_u *UserUpdate) AddGender(v usertype.Gender) *UserUpdate {
	_u.mutation.AddGender(v)
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserUpdate) ClearGender() *UserUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetUserPassword sets the "user_password" field.
func (_u *UserUpdate) SetUserPassword(v string) *UserUpdate {
	_u.mutation.SetUserPassword(v)
	return _u
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserPassword(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserPassword(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdate) ClearPhone() *UserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserStatus sets the "user_status" field.
func (_u *UserUpdate) SetUserStatus(v int) *UserUpdate {
	_u.mutation.ResetUserStatus()
	_u.mutation.SetUserStatus(v)
	return _u
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserStatus(v *int) *UserUpdate {
	if v != nil {
		_u.SetUserStatus(*v)
	}
	return _u
}

// AddUserStatus adds value to the "user_status" field.
func (_u *UserUpdate) AddUserStatus(v int) *UserUpdate {
	_u.mutation.AddUserStatus(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdate) SetUpdateTime(v time.Time) *UserUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserUpdate) SetIsDelete(v int8) *UserUpdate {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserUpdate) SetNillableIsDelete(v *int8) *UserUpdate {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *UserUpdate) AddIsDelete(v int8) *UserUpdate {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *UserUpdate) SetUserRole(v int) *UserUpdate {
	_u.mutation.ResetUserRole()
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserRole(v *int) *UserUpdate {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// AddUserRole adds value to the "user_role" field.
func (_u *UserUpdate) AddUserRole(v int) *UserUpdate {
	_u.mutation.AddUserRole(v)
	return _u
}

// SetPlanetCode sets the "planet_code" field.
func (_u *UserUpdate) SetPlanetCode(v string) *UserUpdate {
	_u.mutation.SetPlanetCode(v)
	return _u
}

// SetNillablePlanetCode sets the "planet_code" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePlanetCode(v *string) *UserUpdate {
	if v != nil {
		_u.SetPlanetCode(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdate) SetTags(v string) *UserUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *UserUpdate) SetNillableTags(v *string) *UserUpdate {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdate) ClearTags() *UserUpdate {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := user.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "User.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := user.GenderValidator(int8(v)); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "User.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanetCode(); ok {
		if err := user.PlanetCodeValidator(v); err != nil {
			return &ValidationError{Name: "planet_code", err: fmt.Errorf(`ent: validator failed for field "User.planet_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tags(); ok {
		if err := user.TagsValidator(v); err != nil {
			return &ValidationError{Name: "tags", err: fmt.Errorf(`ent: validator failed for field "User.tags": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedGender(); ok {
		_spec.AddField(user.FieldGender, field.TypeInt8, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(user.FieldGender, field.TypeInt8)
	}
	if value, ok := _u.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserStatus(); ok {
		_spec.SetField(user.FieldUserStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserStatus(); ok {
		_spec.AddField(user.FieldUserStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(user.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserRole(); ok {
		_spec.AddField(user.FieldUserRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanetCode(); ok {
		_spec.SetField(user.FieldPlanetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(user.FieldTags, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *UserUpdateOne) ClearUsername() *UserUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetUserAccount sets the "user_account" field.
func (_u *UserUpdateOne) SetUserAccount(v string) *UserUpdateOne {
	_u.mutation.SetUserAccount(v)
	return _u
}

// SetNillableUserAccount sets the "user_account" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserAccount(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserAccount(*v)
	}
	return _u
}

// SetAvatarURL sets the "avatar_url" field.
func (_u *UserUpdateOne) SetAvatarURL(v string) *UserUpdateOne {
	_u.mutation.SetAvatarURL(v)
	return _u
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatarURL(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatarURL(*v)
	}
	return _u
}

// ClearAvatarURL clears the value of the "avatar_url" field.
func (_u *UserUpdateOne) ClearAvatarURL() *UserUpdateOne {
	_u.mutation.ClearAvatarURL()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdateOne) SetGender(v usertype.Gender) *UserUpdateOne {
	_u.mutation.ResetGender()
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGender(v *usertype.Gender) *UserUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// AddGender adds value to the "gender" field.
func (_u *UserUpdateOne) AddGender(v usertype.Gender) *UserUpdateOne {
	_u.mutation.AddGender(v)
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserUpdateOne) ClearGender() *UserUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetUserPassword sets the "user_password" field.
func (_u *UserUpdateOne) SetUserPassword(v string) *UserUpdateOne {
	_u.mutation.SetUserPassword(v)
	return _u
}

// SetNillableUserPassword sets the "user_password" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserPassword(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserPassword(*v)
	}
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdateOne) ClearPhone() *UserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserStatus sets the "user_status" field.
func (_u *UserUpdateOne) SetUserStatus(v int) *UserUpdateOne {
	_u.mutation.ResetUserStatus()
	_u.mutation.SetUserStatus(v)
	return _u
}

// SetNillableUserStatus sets the "user_status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserStatus(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetUserStatus(*v)
	}
	return _u
}

// AddUserStatus adds value to the "user_status" field.
func (_u *UserUpdateOne) AddUserStatus(v int) *UserUpdateOne {
	_u.mutation.AddUserStatus(v)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UserUpdateOne) SetUpdateTime(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetIsDelete sets the "is_delete" field.
func (_u *UserUpdateOne) SetIsDelete(v int8) *UserUpdateOne {
	_u.mutation.ResetIsDelete()
	_u.mutation.SetIsDelete(v)
	return _u
}

// SetNillableIsDelete sets the "is_delete" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableIsDelete(v *int8) *UserUpdateOne {
	if v != nil {
		_u.SetIsDelete(*v)
	}
	return _u
}

// AddIsDelete adds value to the "is_delete" field.
func (_u *UserUpdateOne) AddIsDelete(v int8) *UserUpdateOne {
	_u.mutation.AddIsDelete(v)
	return _u
}

// SetUserRole sets the "user_role" field.
func (_u *UserUpdateOne) SetUserRole(v int) *UserUpdateOne {
	_u.mutation.ResetUserRole()
	_u.mutation.SetUserRole(v)
	return _u
}

// SetNillableUserRole sets the "user_role" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserRole(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetUserRole(*v)
	}
	return _u
}

// AddUserRole adds value to the "user_role" field.
func (_u *UserUpdateOne) AddUserRole(v int) *UserUpdateOne {
	_u.mutation.AddUserRole(v)
	return _u
}

// SetPlanetCode sets the "planet_code" field.
func (_u *UserUpdateOne) SetPlanetCode(v string) *UserUpdateOne {
	_u.mutation.SetPlanetCode(v)
	return _u
}

// SetNillablePlanetCode sets the "planet_code" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePlanetCode(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPlanetCode(*v)
	}
	return _u
}

// SetTags sets the "tags" field.
func (_u *UserUpdateOne) SetTags(v string) *UserUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// SetNillableTags sets the "tags" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableTags(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetTags(*v)
	}
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *UserUpdateOne) ClearTags() *UserUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := user.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserAccount(); ok {
		if err := user.UserAccountValidator(v); err != nil {
			return &ValidationError{Name: "user_account", err: fmt.Errorf(`ent: validator failed for field "User.user_account": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AvatarURL(); ok {
		if err := user.AvatarURLValidator(v); err != nil {
			return &ValidationError{Name: "avatar_url", err: fmt.Errorf(`ent: validator failed for field "User.avatar_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Gender(); ok {
		if err := user.GenderValidator(int8(v)); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "User.gender": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserPassword(); ok {
		if err := user.UserPasswordValidator(v); err != nil {
			return &ValidationError{Name: "user_password", err: fmt.Errorf(`ent: validator failed for field "User.user_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Phone(); ok {
		if err := user.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "User.phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := user.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "User.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PlanetCode(); ok {
		if err := user.PlanetCodeValidator(v); err != nil {
			return &ValidationError{Name: "planet_code", err: fmt.Errorf(`ent: validator failed for field "User.planet_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Tags(); ok {
		if err := user.TagsValidator(v); err != nil {
			return &ValidationError{Name: "tags", err: fmt.Errorf(`ent: validator failed for field "User.tags": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(user.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.UserAccount(); ok {
		_spec.SetField(user.FieldUserAccount, field.TypeString, value)
	}
	if value, ok := _u.mutation.AvatarURL(); ok {
		_spec.SetField(user.FieldAvatarURL, field.TypeString, value)
	}
	if _u.mutation.AvatarURLCleared() {
		_spec.ClearField(user.FieldAvatarURL, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedGender(); ok {
		_spec.AddField(user.FieldGender, field.TypeInt8, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(user.FieldGender, field.TypeInt8)
	}
	if value, ok := _u.mutation.UserPassword(); ok {
		_spec.SetField(user.FieldUserPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserStatus(); ok {
		_spec.SetField(user.FieldUserStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserStatus(); ok {
		_spec.AddField(user.FieldUserStatus, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(user.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsDelete(); ok {
		_spec.SetField(user.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedIsDelete(); ok {
		_spec.AddField(user.FieldIsDelete, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.UserRole(); ok {
		_spec.SetField(user.FieldUserRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserRole(); ok {
		_spec.AddField(user.FieldUserRole, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PlanetCode(); ok {
		_spec.SetField(user.FieldPlanetCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(user.FieldTags, field.TypeString, value)
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(user.FieldTags, field.TypeString)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
