// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldUserAccount holds the string denoting the user_account field in the database.
	FieldUserAccount = "user_account"
	// FieldAvatarURL holds the string denoting the avatar_url field in the database.
	FieldAvatarURL = "avatar_url"
	// FieldGender holds the string denoting the gender field in the database.
	FieldGender = "gender"
	// FieldUserPassword holds the string denoting the user_password field in the database.
	FieldUserPassword = "user_password"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldUserStatus holds the string denoting the user_status field in the database.
	FieldUserStatus = "user_status"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldIsDelete holds the string denoting the is_delete field in the database.
	FieldIsDelete = "is_delete"
	// FieldUserRole holds the string denoting the user_role field in the database.
	FieldUserRole = "user_role"
	// FieldPlanetCode holds the string denoting the planet_code field in the database.
	FieldPlanetCode = "planet_code"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// EdgeLedTeams holds the string denoting the led_teams edge name in mutations.
	EdgeLedTeams = "led_teams"
	// EdgeTeamMemberships holds the string denoting the team_memberships edge name in mutations.
	EdgeTeamMemberships = "team_memberships"
	// Table holds the table name of the user in the database.
	Table = "user"
	// LedTeamsTable is the table that holds the led_teams relation/edge.
	LedTeamsTable = "team"
	// LedTeamsInverseTable is the table name for the Team entity.
	// It exists in this package in order to avoid circular dependency with the "team" package.
	LedTeamsInverseTable = "team"
	// LedTeamsColumn is the table column denoting the led_teams relation/edge.
	LedTeamsColumn = "user_id"
	// TeamMembershipsTable is the table that holds the team_memberships relation/edge.
	TeamMembershipsTable = "user_team"
	// TeamMembershipsInverseTable is the table name for the UserTeam entity.
	// It exists in this package in order to avoid circular dependency with the "userteam" package.
	TeamMembershipsInverseTable = "user_team"
	// TeamMembershipsColumn is the table column denoting the team_memberships relation/edge.
	TeamMembershipsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldUserAccount,
	FieldAvatarURL,
	FieldGender,
	FieldUserPassword,
	FieldPhone,
	FieldEmail,
	FieldUserStatus,
	FieldCreateTime,
	FieldUpdateTime,
	FieldIsDelete,
	FieldUserRole,
	FieldPlanetCode,
	FieldTags,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// UserAccountValidator is a validator for the "user_account" field. It is called by the builders before save.
	UserAccountValidator func(string) error
	// AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	AvatarURLValidator func(string) error
	// GenderValidator is a validator for the "gender" field. It is called by the builders before save.
	GenderValidator func(int8) error
	// UserPasswordValidator is a validator for the "user_password" field. It is called by the builders before save.
	UserPasswordValidator func(string) error
	// PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	PhoneValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// DefaultUserStatus holds the default value on creation for the "user_status" field.
	DefaultUserStatus int
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultIsDelete holds the default value on creation for the "is_delete" field.
	DefaultIsDelete int8
	// DefaultUserRole holds the default value on creation for the "user_role" field.
	DefaultUserRole int
	// PlanetCodeValidator is a validator for the "planet_code" field. It is called by the builders before save.
	PlanetCodeValidator func(string) error
	// TagsValidator is a validator for the "tags" field. It is called by the builders before save.
	TagsValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByUserAccount orders the results by the user_account field.
func ByUserAccount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserAccount, opts...).ToFunc()
}

// ByAvatarURL orders the results by the avatar_url field.
func ByAvatarURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarURL, opts...).ToFunc()
}

// ByGender orders the results by the gender field.
func ByGender(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGender, opts...).ToFunc()
}

// ByUserPassword orders the results by the user_password field.
func ByUserPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserPassword, opts...).ToFunc()
}

// ByPhone orders the results by the phone field.
func ByPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPhone, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByUserStatus orders the results by the user_status field.
func ByUserStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserStatus, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByIsDelete orders the results by the is_delete field.
func ByIsDelete(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDelete, opts...).ToFunc()
}

// ByUserRole orders the results by the user_role field.
func ByUserRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserRole, opts...).ToFunc()
}

// ByPlanetCode orders the results by the planet_code field.
func ByPlanetCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanetCode, opts...).ToFunc()
}

// ByTags orders the results by the tags field.
func ByTags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTags, opts...).ToFunc()
}

// ByLedTeamsCount orders the results by led_teams count.
func ByLedTeamsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLedTeamsStep(), opts...)
	}
}

// ByLedTeams orders the results by led_teams terms.
func ByLedTeams(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLedTeamsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTeamMembershipsCount orders the results by team_memberships count.
func ByTeamMembershipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTeamMembershipsStep(), opts...)
	}
}

// ByTeamMemberships orders the results by team_memberships terms.
func ByTeamMemberships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTeamMembershipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newLedTeamsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LedTeamsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LedTeamsTable, LedTeamsColumn),
	)
}
func newTeamMembershipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TeamMembershipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TeamMembershipsTable, TeamMembershipsColumn),
	)
}
