// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"
	"yupao-go/ent/predicate"
	"yupao-go/internal/pkg/types"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UserAccount applies equality check predicate on the "user_account" field. It's identical to UserAccountEQ.
func UserAccount(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAccount, v))
}

// AvatarURL applies equality check predicate on the "avatar_url" field. It's identical to AvatarURLEQ.
func AvatarURL(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// Gender applies equality check predicate on the "gender" field. It's identical to GenderEQ.
func Gender(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldEQ(FieldGender, vc))
}

// UserPassword applies equality check predicate on the "user_password" field. It's identical to UserPasswordEQ.
func UserPassword(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserPassword, v))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// UserStatus applies equality check predicate on the "user_status" field. It's identical to UserStatusEQ.
func UserStatus(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserStatus, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdateTime, v))
}

// IsDelete applies equality check predicate on the "is_delete" field. It's identical to IsDeleteEQ.
func IsDelete(v int8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsDelete, v))
}

// UserRole applies equality check predicate on the "user_role" field. It's identical to UserRoleEQ.
func UserRole(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserRole, v))
}

// PlanetCode applies equality check predicate on the "planet_code" field. It's identical to PlanetCodeEQ.
func PlanetCode(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPlanetCode, v))
}

// Tags applies equality check predicate on the "tags" field. It's identical to TagsEQ.
func Tags(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTags, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameIsNil applies the IsNil predicate on the "username" field.
func UsernameIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldUsername))
}

// UsernameNotNil applies the NotNil predicate on the "username" field.
func UsernameNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldUsername))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUsername, v))
}

// UserAccountEQ applies the EQ predicate on the "user_account" field.
func UserAccountEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserAccount, v))
}

// UserAccountNEQ applies the NEQ predicate on the "user_account" field.
func UserAccountNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserAccount, v))
}

// UserAccountIn applies the In predicate on the "user_account" field.
func UserAccountIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserAccount, vs...))
}

// UserAccountNotIn applies the NotIn predicate on the "user_account" field.
func UserAccountNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserAccount, vs...))
}

// UserAccountGT applies the GT predicate on the "user_account" field.
func UserAccountGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserAccount, v))
}

// UserAccountGTE applies the GTE predicate on the "user_account" field.
func UserAccountGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserAccount, v))
}

// UserAccountLT applies the LT predicate on the "user_account" field.
func UserAccountLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserAccount, v))
}

// UserAccountLTE applies the LTE predicate on the "user_account" field.
func UserAccountLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserAccount, v))
}

// UserAccountContains applies the Contains predicate on the "user_account" field.
func UserAccountContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserAccount, v))
}

// UserAccountHasPrefix applies the HasPrefix predicate on the "user_account" field.
func UserAccountHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserAccount, v))
}

// UserAccountHasSuffix applies the HasSuffix predicate on the "user_account" field.
func UserAccountHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserAccount, v))
}

// UserAccountEqualFold applies the EqualFold predicate on the "user_account" field.
func UserAccountEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserAccount, v))
}

// UserAccountContainsFold applies the ContainsFold predicate on the "user_account" field.
func UserAccountContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserAccount, v))
}

// AvatarURLEQ applies the EQ predicate on the "avatar_url" field.
func AvatarURLEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarURL, v))
}

// AvatarURLNEQ applies the NEQ predicate on the "avatar_url" field.
func AvatarURLNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarURL, v))
}

// AvatarURLIn applies the In predicate on the "avatar_url" field.
func AvatarURLIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarURL, vs...))
}

// AvatarURLNotIn applies the NotIn predicate on the "avatar_url" field.
func AvatarURLNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarURL, vs...))
}

// AvatarURLGT applies the GT predicate on the "avatar_url" field.
func AvatarURLGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarURL, v))
}

// AvatarURLGTE applies the GTE predicate on the "avatar_url" field.
func AvatarURLGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarURL, v))
}

// AvatarURLLT applies the LT predicate on the "avatar_url" field.
func AvatarURLLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarURL, v))
}

// AvatarURLLTE applies the LTE predicate on the "avatar_url" field.
func AvatarURLLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarURL, v))
}

// AvatarURLContains applies the Contains predicate on the "avatar_url" field.
func AvatarURLContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarURL, v))
}

// AvatarURLHasPrefix applies the HasPrefix predicate on the "avatar_url" field.
func AvatarURLHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarURL, v))
}

// AvatarURLHasSuffix applies the HasSuffix predicate on the "avatar_url" field.
func AvatarURLHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarURL, v))
}

// AvatarURLIsNil applies the IsNil predicate on the "avatar_url" field.
func AvatarURLIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarURL))
}

// AvatarURLNotNil applies the NotNil predicate on the "avatar_url" field.
func AvatarURLNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarURL))
}

// AvatarURLEqualFold applies the EqualFold predicate on the "avatar_url" field.
func AvatarURLEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarURL, v))
}

// AvatarURLContainsFold applies the ContainsFold predicate on the "avatar_url" field.
func AvatarURLContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarURL, v))
}

// GenderEQ applies the EQ predicate on the "gender" field.
func GenderEQ(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldEQ(FieldGender, vc))
}

// GenderNEQ applies the NEQ predicate on the "gender" field.
func GenderNEQ(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldNEQ(FieldGender, vc))
}

// GenderIn applies the In predicate on the "gender" field.
func GenderIn(vs ...types.Gender) predicate.User {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.User(sql.FieldIn(FieldGender, v...))
}

// GenderNotIn applies the NotIn predicate on the "gender" field.
func GenderNotIn(vs ...types.Gender) predicate.User {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = int8(vs[i])
	}
	return predicate.User(sql.FieldNotIn(FieldGender, v...))
}

// GenderGT applies the GT predicate on the "gender" field.
func GenderGT(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldGT(FieldGender, vc))
}

// GenderGTE applies the GTE predicate on the "gender" field.
func GenderGTE(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldGTE(FieldGender, vc))
}

// GenderLT applies the LT predicate on the "gender" field.
func GenderLT(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldLT(FieldGender, vc))
}

// GenderLTE applies the LTE predicate on the "gender" field.
func GenderLTE(v types.Gender) predicate.User {
	vc := int8(v)
	return predicate.User(sql.FieldLTE(FieldGender, vc))
}

// GenderIsNil applies the IsNil predicate on the "gender" field.
func GenderIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldGender))
}

// GenderNotNil applies the NotNil predicate on the "gender" field.
func GenderNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldGender))
}

// UserPasswordEQ applies the EQ predicate on the "user_password" field.
func UserPasswordEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserPassword, v))
}

// UserPasswordNEQ applies the NEQ predicate on the "user_password" field.
func UserPasswordNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserPassword, v))
}

// UserPasswordIn applies the In predicate on the "user_password" field.
func UserPasswordIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserPassword, vs...))
}

// UserPasswordNotIn applies the NotIn predicate on the "user_password" field.
func UserPasswordNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserPassword, vs...))
}

// UserPasswordGT applies the GT predicate on the "user_password" field.
func UserPasswordGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserPassword, v))
}

// UserPasswordGTE applies the GTE predicate on the "user_password" field.
func UserPasswordGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserPassword, v))
}

// UserPasswordLT applies the LT predicate on the "user_password" field.
func UserPasswordLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserPassword, v))
}

// UserPasswordLTE applies the LTE predicate on the "user_password" field.
func UserPasswordLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserPassword, v))
}

// UserPasswordContains applies the Contains predicate on the "user_password" field.
func UserPasswordContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldUserPassword, v))
}

// UserPasswordHasPrefix applies the HasPrefix predicate on the "user_password" field.
func UserPasswordHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldUserPassword, v))
}

// UserPasswordHasSuffix applies the HasSuffix predicate on the "user_password" field.
func UserPasswordHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldUserPassword, v))
}

// UserPasswordEqualFold applies the EqualFold predicate on the "user_password" field.
func UserPasswordEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldUserPassword, v))
}

// UserPasswordContainsFold applies the ContainsFold predicate on the "user_password" field.
func UserPasswordContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldUserPassword, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneIsNil applies the IsNil predicate on the "phone" field.
func PhoneIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldPhone))
}

// PhoneNotNil applies the NotNil predicate on the "phone" field.
func PhoneNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldPhone))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPhone, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailIsNil applies the IsNil predicate on the "email" field.
func EmailIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldEmail))
}

// EmailNotNil applies the NotNil predicate on the "email" field.
func EmailNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldEmail))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// UserStatusEQ applies the EQ predicate on the "user_status" field.
func UserStatusEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserStatus, v))
}

// UserStatusNEQ applies the NEQ predicate on the "user_status" field.
func UserStatusNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserStatus, v))
}

// UserStatusIn applies the In predicate on the "user_status" field.
func UserStatusIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserStatus, vs...))
}

// UserStatusNotIn applies the NotIn predicate on the "user_status" field.
func UserStatusNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserStatus, vs...))
}

// UserStatusGT applies the GT predicate on the "user_status" field.
func UserStatusGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserStatus, v))
}

// UserStatusGTE applies the GTE predicate on the "user_status" field.
func UserStatusGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserStatus, v))
}

// UserStatusLT applies the LT predicate on the "user_status" field.
func UserStatusLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserStatus, v))
}

// UserStatusLTE applies the LTE predicate on the "user_status" field.
func UserStatusLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserStatus, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreateTime, v))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUpdateTime, v))
}

// IsDeleteEQ applies the EQ predicate on the "is_delete" field.
func IsDeleteEQ(v int8) predicate.User {
	return predicate.User(sql.FieldEQ(FieldIsDelete, v))
}

// IsDeleteNEQ applies the NEQ predicate on the "is_delete" field.
func IsDeleteNEQ(v int8) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldIsDelete, v))
}

// IsDeleteIn applies the In predicate on the "is_delete" field.
func IsDeleteIn(vs ...int8) predicate.User {
	return predicate.User(sql.FieldIn(FieldIsDelete, vs...))
}

// IsDeleteNotIn applies the NotIn predicate on the "is_delete" field.
func IsDeleteNotIn(vs ...int8) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldIsDelete, vs...))
}

// IsDeleteGT applies the GT predicate on the "is_delete" field.
func IsDeleteGT(v int8) predicate.User {
	return predicate.User(sql.FieldGT(FieldIsDelete, v))
}

// IsDeleteGTE applies the GTE predicate on the "is_delete" field.
func IsDeleteGTE(v int8) predicate.User {
	return predicate.User(sql.FieldGTE(FieldIsDelete, v))
}

// IsDeleteLT applies the LT predicate on the "is_delete" field.
func IsDeleteLT(v int8) predicate.User {
	return predicate.User(sql.FieldLT(FieldIsDelete, v))
}

// IsDeleteLTE applies the LTE predicate on the "is_delete" field.
func IsDeleteLTE(v int8) predicate.User {
	return predicate.User(sql.FieldLTE(FieldIsDelete, v))
}

// UserRoleEQ applies the EQ predicate on the "user_role" field.
func UserRoleEQ(v int) predicate.User {
	return predicate.User(sql.FieldEQ(FieldUserRole, v))
}

// UserRoleNEQ applies the NEQ predicate on the "user_role" field.
func UserRoleNEQ(v int) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldUserRole, v))
}

// UserRoleIn applies the In predicate on the "user_role" field.
func UserRoleIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldIn(FieldUserRole, vs...))
}

// UserRoleNotIn applies the NotIn predicate on the "user_role" field.
func UserRoleNotIn(vs ...int) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldUserRole, vs...))
}

// UserRoleGT applies the GT predicate on the "user_role" field.
func UserRoleGT(v int) predicate.User {
	return predicate.User(sql.FieldGT(FieldUserRole, v))
}

// UserRoleGTE applies the GTE predicate on the "user_role" field.
func UserRoleGTE(v int) predicate.User {
	return predicate.User(sql.FieldGTE(FieldUserRole, v))
}

// UserRoleLT applies the LT predicate on the "user_role" field.
func UserRoleLT(v int) predicate.User {
	return predicate.User(sql.FieldLT(FieldUserRole, v))
}

// UserRoleLTE applies the LTE predicate on the "user_role" field.
func UserRoleLTE(v int) predicate.User {
	return predicate.User(sql.FieldLTE(FieldUserRole, v))
}

// PlanetCodeEQ applies the EQ predicate on the "planet_code" field.
func PlanetCodeEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldPlanetCode, v))
}

// PlanetCodeNEQ applies the NEQ predicate on the "planet_code" field.
func PlanetCodeNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldPlanetCode, v))
}

// PlanetCodeIn applies the In predicate on the "planet_code" field.
func PlanetCodeIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldPlanetCode, vs...))
}

// PlanetCodeNotIn applies the NotIn predicate on the "planet_code" field.
func PlanetCodeNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldPlanetCode, vs...))
}

// PlanetCodeGT applies the GT predicate on the "planet_code" field.
func PlanetCodeGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldPlanetCode, v))
}

// PlanetCodeGTE applies the GTE predicate on the "planet_code" field.
func PlanetCodeGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldPlanetCode, v))
}

// PlanetCodeLT applies the LT predicate on the "planet_code" field.
func PlanetCodeLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldPlanetCode, v))
}

// PlanetCodeLTE applies the LTE predicate on the "planet_code" field.
func PlanetCodeLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldPlanetCode, v))
}

// PlanetCodeContains applies the Contains predicate on the "planet_code" field.
func PlanetCodeContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldPlanetCode, v))
}

// PlanetCodeHasPrefix applies the HasPrefix predicate on the "planet_code" field.
func PlanetCodeHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldPlanetCode, v))
}

// PlanetCodeHasSuffix applies the HasSuffix predicate on the "planet_code" field.
func PlanetCodeHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldPlanetCode, v))
}

// PlanetCodeEqualFold applies the EqualFold predicate on the "planet_code" field.
func PlanetCodeEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldPlanetCode, v))
}

// PlanetCodeContainsFold applies the ContainsFold predicate on the "planet_code" field.
func PlanetCodeContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldPlanetCode, v))
}

// TagsEQ applies the EQ predicate on the "tags" field.
func TagsEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldTags, v))
}

// TagsNEQ applies the NEQ predicate on the "tags" field.
func TagsNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldTags, v))
}

// TagsIn applies the In predicate on the "tags" field.
func TagsIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldTags, vs...))
}

// TagsNotIn applies the NotIn predicate on the "tags" field.
func TagsNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldTags, vs...))
}

// TagsGT applies the GT predicate on the "tags" field.
func TagsGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldTags, v))
}

// TagsGTE applies the GTE predicate on the "tags" field.
func TagsGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldTags, v))
}

// TagsLT applies the LT predicate on the "tags" field.
func TagsLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldTags, v))
}

// TagsLTE applies the LTE predicate on the "tags" field.
func TagsLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldTags, v))
}

// TagsContains applies the Contains predicate on the "tags" field.
func TagsContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldTags, v))
}

// TagsHasPrefix applies the HasPrefix predicate on the "tags" field.
func TagsHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldTags, v))
}

// TagsHasSuffix applies the HasSuffix predicate on the "tags" field.
func TagsHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldTags, v))
}

// TagsIsNil applies the IsNil predicate on the "tags" field.
func TagsIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldTags))
}

// TagsNotNil applies the NotNil predicate on the "tags" field.
func TagsNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldTags))
}

// TagsEqualFold applies the EqualFold predicate on the "tags" field.
func TagsEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldTags, v))
}

// TagsContainsFold applies the ContainsFold predicate on the "tags" field.
func TagsContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldTags, v))
}

// HasLedTeams applies the HasEdge predicate on the "led_teams" edge.
func HasLedTeams() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LedTeamsTable, LedTeamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLedTeamsWith applies the HasEdge predicate on the "led_teams" edge with a given conditions (other predicates).
func HasLedTeamsWith(preds ...predicate.Team) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newLedTeamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeamMemberships applies the HasEdge predicate on the "team_memberships" edge.
func HasTeamMemberships() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TeamMembershipsTable, TeamMembershipsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamMembershipsWith applies the HasEdge predicate on the "team_memberships" edge with a given conditions (other predicates).
func HasTeamMembershipsWith(preds ...predicate.UserTeam) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newTeamMembershipsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
